DROP DATABASE IF EXISTS greatbay;

CREATE DATABASE greatbay;

USE greatbay;

CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  firstname VARCHAR(45) NOT NULL,
  lastname VARCHAR(45) NOT NULL,
  streetaddress1 VARCHAR(45) ,
  streetaddress2 VARCHAR(45),
  city VARCHAR(45) ,
  state VARCHAR(45) ,

);

CREATE TABLE items (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  item VARCHAR(45) NOT NULL,
  description VARCHAR(45) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  quantity INT NOT NULL NULL,
);

CREATE TABLE auctions (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(45) NOT NULL,
  startdate INT NOT NULL,
  enddate INT NOT NULL,
  sellerid INT NOT NULL AUTO_INCREMENT,
);

CREATE TABLE bids (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  bidderid INT NOT NULL AUTO_INCREMENT,
  itemid INT NOT NULL AUTO_INCREMENT,
  price INT NOT NULL,
);

CREATE TABLE itemsInAuction(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  itemid INT NOT NULL AUTO_INCREMENT,
  auctionid INT NOT NULL AUTO_INCREMENT,
  startingprice DECIMAL(10,2) NOT NULL,
);

